[platformio]
src_dir = firmware/src

[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = firmware/partitions_factory.csv
lib_deps =
  adafruit/Adafruit SHT31 Library@^2.2.2
  mikalhart/TinyGPSPlus@^1.1.0
  tzapu/WiFiManager@^2.0.17
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^4.0.4
  bogde/HX711@^0.7.5
