[platformio]
src_dir = firmware/src

[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
lib_deps =
  adafruit/Adafruit SHT31 Library@^2.2.2
  mikalhart/TinyGPSPlus@^1.1.0
  tzapu/WiFiManager@^2.0.17
